### ISSUE TITLE
makefile has problems on windows

### ISSUE THREAD

**Issue by u8mydog** [multiwii/baseflight#135]
The slashes for 'mkdir' fail when running make on a windows machine. In order to fix it on windows (and it should still work on linux), I added the following macro:
ifeq ($(OS),Windows_NT)
	MKDIR_OBJDIR = @if not exist $(OBJECT_DIR) mkdir $(subst /,\,$(dir $@))
else
	MKDIR_OBJDIR = @mkdir -p $(dir $@)
endif

and replaced the three lines (207,213,217) that contain a call to 'mkdir' with the following:
	$(MKDIR_OBJDIR)

There are other issues with the makefile on windows but the above changes allow the project to be built.

**Comment by fiendie** [comment]
@u8mydog https://github.com/multiwii/baseflight/pull/257
