### ISSUE TITLE
PID function observations

### ISSUE THREAD

**Issue by ChrisNisbet01** [multiwii/baseflight#151]
Hi
I have been looking through the PID functions and have found a few things that I would like to ask about.

In pidRewrite() I see this line (~382)...
            errorAngle = (constrain(rcCommand[axis] + GPS_angle[axis], -500, +500) - angle[axis] + cfg.angleTrim[axis]) / 10.0f; // 16 bits is ok here
I found the division by 10.0f at the end a bit odd as the rest of the variables (including where the result is placed) are integers. Shouldn't the divisor just be 10?
Also, if the division by 10 is required, wouldn't it be better to do it _after_ it has been multiplied by the constants, so as to lose less resolution?
I'm thinking that it might also be worth doing some rounding before the division as well.

On the same line, I see the constants -500 and +500, used as limits for the setpoint angle. Shouldn't mcfg.max_angle_inclination be used as the limit as it is in the other PID function?

I got to wondering about the division by 10.0f, and when it was added into the code, and it turns out that it was added with commit b32cc09e (25 May 2014) that has this associated comment.
"move code around to fix some gcc error that doesn't occur with real compilers"

In the code this commit replaced, there was no division by 10, and mcfg.max_angle_inclination had been used in place of the constants -500 and 500. 

The comment doesn't explain the addition for the division by 10.0f or the replacement of mcfg.max_angle_inclination with the constants either. On my machine at least, 
I get no strange gcc warnings, and the original C code doesn't look convoluted enough to cause the compiler to emit any dodgy instructions. Is this what was happening?

I thought I would do a little more digging, and it appears that this line was taken from a different PID function (pidBaseflight) that was first introduced with commit b996b26c, which was made before the mcfg.max_angle_inclination setting was added, which probably explains why the constants are used. This other function also used floats rather than integers, which also explains the division by 10.0f.

Anyway, the upshot of this is that I'm wondering if the commit that added this line to pidRewrite was done in error.

I've also had an idea about the calculation of the D term in pidRewrite. I see that at the moment that the D term is determined from changes in RateError, which is determined
from the input variable and also from changes in the setpoint (rcCommand[axis]). What this means is that changes in setpoint (even small changes) will result in a kick in the D term.
Is this what you're after? Changes in setpoint can act a little bit like noise and create an undesirable D term.
What can be done to avoid this is to calculate the D term from changes to the input variable only, and not changes to the error. You can see that if the setpoint is constant, 
changes in error have the same value as changes in the process variable, so there would be no difference to the calculate D term if the setpoint is constant. 
However, if the D term is calculated from changes in the process variable only, changes in the setpoint will not result in large kicks in the D term. 
This is often a good thing, although I'm not sure that's what's needed with a flight controller.
Looking at the code, it seems that this sort of approach might only be useful when in ANGLE mode, which determines the error from the angle[axis] variable (and the stick positions). 
Changes in the angle[axis] variable could be used directly rather than changes in the error to determine the D term, leaving rcCommand[axis] out of it.
Anyway, just a thought.

**Comment by fiendie** [comment]
No longer relevant according to @luggi 
https://github.com/multiwii/multiwii-firmware/blob/upstream_shared/MultiWii.cpp#L1463
