### ISSUE TITLE
Servo output no longer re-centers itself to mid after changing rate % in servo tab

### ISSUE THREAD

**Issue by creyc** [multiwii/baseflight#246]
This issue can be demonstrated in the 2015.02.12 firmware by setting the airplane mixer then changing any servo to 'Rate: -100%' in the servo tab then checking that servo's output in the Motor Testing tab.  Expected output is MID setting, but instead getting MIN.

This issue first shows up in the Dev 2014.12.08 build, but was working correctly in Stable 2014.12.04 build.

**Comment by ShikOfTheRa** [comment]
I am seeing the same issue

**Comment by fiendie** [comment]
@schugabe is currently working on MSP for the new servo mixer. As soon as that's done the servo tab can be fixed by @ctn-dev

**Comment by schugabe** [comment]
Can someone test the fix I just pushed?

**Comment by cTn-dev** [comment]
Any word on this one ?

**Comment by creyc** [comment]
@schugabe rate values < 0% seem to work correctly now in my testing, thanks!

**Comment by schugabe** [comment]
Great! Can someone close this issue?

**Comment by ShikOfTheRa** [comment]
Seems to work for me too.. Muchos Gracias

**Comment by fiendie** [comment]
@schugabe thanks a lot ;)
