### ISSUE TITLE
I2C error while using I2C1

### ISSUE THREAD

**Issue by 19504643** [multiwii/baseflight#282]
I want to port baseflight to another board,the mcu is stm32f103ret6,and I connect mpu6050 hmc5883l ms5611 to its I2C1,I just modified the code 
,        #define I2C_DEVICE (I2CDEV_1)    //board.h
and it would halt at 
,        while (I2Cx->CR1 & 0x0100)            //drv_i2c.c
in FUNCTION 
,        i2c_er_handler  (LINE179) 
in drv_i2c.c,but why?

**Comment by trollcop** [comment]
Try using SOFT_I2C, or else be prepared to debug with a scope and by stepping through code.

**Comment by trollcop** [comment]
Pretty sure this was fixed before.
