### ISSUE TITLE
"feature SERIALRX" INVALID

### ISSUE THREAD

**Issue by trishhyles** [multiwii/baseflight#290]
in BF configurator, into CLI and type feature SERIALRX, appear invalid feature name

**Comment by trishhyles** [comment]
Emmm, how to upload a pic to confirm it this issue...

**Comment by trollcop** [comment]
I'll do it for you:

![image](https://cloud.githubusercontent.com/assets/4640472/8893353/358e1fee-33c8-11e5-90c4-8cb063f0bd5a.png)

**Comment by trollcop** [comment]
Stop opening issues related to @hydra joblessflightconfigurator
