### ISSUE TITLE
Sensor calibration code

### ISSUE THREAD

**Issue by Redifei** [multiwii/baseflight#292]
Hello. I had a question than at the ACC_Common function in the file of sensor.c baseflight source code.

'a[ROLL] + (CALIBRATING_ACC_CYCLES / 2)) / CALIBRATING_ACC_CYCLES'

The above source code, not the source code to calculate the average. The above source code is average + '1/2'

So I wonder why that code is written like that.

**Comment by luggi** [comment]
rounding

**Comment by Redifei** [comment]
Haha, I forgot that.
Thanks
