### ISSUE TITLE
S.BUS + S.Port on Naze32 Rev6?

### ISSUE THREAD

**Issue by bbbenji** [multiwii/baseflight#308]
Is this possible? I was able to get it configured in Cleanflight but figured since the Naze32 was made for Baseflight I'd go with that. But I am having trouble here.

In CF I used softserial 1 as S.Port on pins 5/6. Here in BF, I'm not so sure.

**Comment by farmertom01** [comment]
Any progress on this? I too would like to use Frsky smartport telemetry on a softserial port. It seems that  Sbus and smartport are now the standard for Frsky receivers. It would be nice if airplanes could use it. 
Thanks

**Comment by wangjun000** [comment]
您好，邮件已经收到！！！！！              这是来自QQ邮箱的自动回复邮件。
