### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by osmartinez** [multiwii/baseflight#314]
> pi@raspberrypi:~/Desktop/baseflight-master $ make
> %% drv_adc.c
> make: arm-none-eabi-gcc: Command not found
> Makefile:211: recipe for target 'obj/NAZE/drv_adc.o' failed
> make: *** [obj/NAZE/drv_adc.o] Error 127

What am I missing to build it up?

**Comment by trollcop** [comment]
https://developer.arm.com/open-source/gnu-toolchain/gnu-rm

**Comment by osmartinez** [comment]
what should I check in that link?

**Comment by trollcop** [comment]
isn't it obvious? the part where you download gcc-arm toolchain for
whatever OS you're using.
