### ISSUE TITLE
Connection Issue "No configuration received within 10 seconds"

### ISSUE THREAD

**Issue by Digipup1** [multiwii/baseflight#315]
I am trying to connect my Beef's Brushed Board flight controller through FTDI using baseflight. And I received that error every time. It is supposed to come pre-flashed with baseflight; however, when I plug in my FTDI USB connected to the flight controller I receive "No configuration received within 10 seconds". 
I am using DSD TECH USB to TTL Serial Adapter with FTDI FT232RL Chip Compatible: [https://www.amazon.com/DSD-TECH-Adapter-FT232RL-Compatible/dp/B07BBPX8B8/ref=redir_mobile_desktop?ie=UTF8&aaxitk=rb-e0tUK.o7hBail1.7hMw&hsa_cr_id=3203181790101&ref_=sb_s_sparkle](url)

**Comment by trollcop** [comment]
You must be lost.
