### ISSUE TITLE
Some CLI commands don't live update or seem to have any effect.

### ISSUE THREAD

**Issue by Felixrising** [multiwii/baseflight#45]
I've noticed that mincommand, yaw_control_direction amongst other things don't seem to live update any more. I think this could be related to servo changes, or perhaps some strange behaviour over MSP when using Baseflight Configurator, in any event, I was only able to get yaw_control_direction to change via the Servo's tab in Configurator and certainly not able to calibrate ESCs via mincommand in CLI.

**Comment by fiendie** [comment]
You are very nitpicky, Felix ;)
